# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.pug"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss,sass}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    # Libraries required by Foundation
    # Core Foundation files
    # Individual Foundation components
    # If you aren't using a component, just remove it from the list

    # Paths to your own project code are here
    - "src/assets/js/!(app).js"
    - "src/assets/js/app.js"
